version: '2'
services:
  web:
    build: .
    command: ["node", "web.js"]
    ports:
     - 80:8000
  worker:
    build: .
    command: ["node", "worker.js"]
    environment:
      - GITHUB_API_TOKEN
